[package]
name = "claws"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
sha2 = "0.8.2"
hex = "0.4.2"
core_affinity = "0.5.10"
wagyu-ethereum = "0.6.3"
wagyu-model = "0.6.3"

